baseURL = "https://schfkt.dev/"
languageCode = "en-us"
title = "schfkt's website"
pygmentsUseClasses = true

[params]
  Description = "schfkt's personal place to share thoughts with the rest of the world"
