#+SETUPFILE: ./setup.org
#+HUGO_DRAFT: false
#+TITLE: About
#+DESCRIPTION: Some words about me

I’m an experienced backend developer mostly focused on Node.js stack, solving problems with TypeScript and sometimes with JavaScript. On top of that I have experience with MongoDB, MySQL (MariaDB) and Redis. Also I’m proficient with Docker and Kubernetes and I have good knowledge of Bash as an automation tool, since I’ve written many scripts for CI/CD pipeline.

I had experience working in a completely remote team for 3 years in the past. That was an interesting challenge, and it really helped me to get better at managing my time and to learn to communicate efficiently.

I’m an avid learner and a very curious person who always tries to get to know how things work under the hood. Since I believe, it’s the best way to truly understand something.

Apart from that, I really like sports: swimming, cycling, running. My goal for this year (2019) is to participate in a triathlon.

* Contacts

+ [[https://www.linkedin.com/in/ivpavig][LinkedIn]]
+ [[https://github.com/schfkt][GitHub]]

Or just [[mailto:ivpavig@gmail.com][drop me a line]].
